# Generated by Django 2.0.13 on 2020-05-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categories', models.TextField(blank=True, max_length=30, null=True, verbose_name='Категории')),
                ('goods', models.TextField(blank=True, null=True, verbose_name='Товары')),
                ('pages', models.TextField(blank=True, null=True, verbose_name='Страницы')),
                ('users', models.TextField(blank=True, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Каталог ',
                'verbose_name_plural': 'Каталоги',
                'db_table': 'catalogmodel',
            },
        ),
    ]
