# Generated by Django 2.0.13 on 2020-05-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(blank=True, max_length=30, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
