# Generated by Django 2.0.13 on 2020-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='float_name',
            field=models.TextField(blank=True, verbose_name='Квартиры'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='photo_arr',
            field=models.TextField(blank=True, verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='photos',
            field=models.TextField(blank=True, verbose_name='Фотография'),
        ),
    ]
