# Generated by Django 2.0.13 on 2020-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200612_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cat_name', models.TextField(blank=True, max_length=30, null=True, verbose_name='Категории')),
                ('cat_url', models.TextField(blank=True, max_length=30, null=True, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categor',
            },
        ),
    ]
