# Generated by Django 2.0.13 on 2020-06-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='price',
            field=models.TextField(blank=True, verbose_name='Цена'),
        ),
    ]
