# Generated by Django 2.0.13 on 2020-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catalogmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='about_the_apartment',
            field=models.TextField(blank=True, verbose_name='О квартире'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
    ]
