# Generated by Django 2.0.13 on 2020-06-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_catalogmodel_apartment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='mortgage',
            field=models.TextField(blank=True, verbose_name='Ипотека'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='object_type',
            field=models.TextField(blank=True, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='owner_phone_number',
            field=models.TextField(blank=True, verbose_name='Телефон собственника'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='plot_hundred',
            field=models.TextField(blank=True, verbose_name='Участок соток'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='quadrature',
            field=models.TextField(blank=True, verbose_name='Квадратура'),
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='type_of_transaction',
            field=models.TextField(blank=True, verbose_name='Тип сделки'),
        ),
    ]
