# Generated by Django 2.0.13 on 2020-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_catalogmodel_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
    ]
