# Generated by Django 2.0.13 on 2020-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orders_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка'),
        ),
    ]
