# Generated by Django 2.0.13 on 2020-07-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_catalogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='загрузить изображение'),
        ),
    ]
