# Generated by Django 2.0.13 on 2020-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_catalogmodel_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='categories',
            field=models.TextField(blank=True, help_text='Новостои 1, Квартиры 2, Дома 3, Аренда 4, Вторичное 5, Зем участки 6, Застройщики 7', max_length=30, null=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='year_in_school',
            field=models.CharField(choices=[('1', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='1', max_length=2),
        ),
    ]
