# Generated by Django 2.0.13 on 2020-07-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200718_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogmodel',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='categories',
            field=models.CharField(choices=[('1', 'Новостройки'), ('2', 'Квартиры'), ('3', 'Дома'), ('4', 'Аренда'), ('5', 'Вторичное'), ('6', 'Земельные участки'), ('7', 'Застройщики ')], default='1', max_length=2),
        ),
    ]
