# Generated by Django 2.0.13 on 2020-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200718_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='number_of_rooms',
            field=models.TextField(blank=True, max_length=30, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='owner_phone_number',
            field=models.TextField(blank=True, max_length=15, verbose_name='Телефон собственника'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='plot_hundred',
            field=models.TextField(blank=True, max_length=10, verbose_name='Участок соток'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='price',
            field=models.TextField(blank=True, max_length=30, verbose_name='Цена'),
        ),
    ]
