# Generated by Django 2.0.13 on 2020-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200718_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='загрузить изображение'),
        ),
    ]
