# Generated by Django 2.0.13 on 2020-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200718_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='загрузить изображение'),
        ),
    ]
