# Generated by Django 2.0.13 on 2020-07-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200719_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='number_of_rooms',
            field=models.CharField(blank=True, max_length=30, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон собственника'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='plot_hundred',
            field=models.CharField(blank=True, max_length=10, verbose_name='Участок соток'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Цена'),
        ),
    ]
