# Generated by Django 2.0.13 on 2020-07-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('main', '0026_auto_20200727_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery', verbose_name='Фотографии'),
        ),
    ]
