# Generated by Django 2.0.13 on 2020-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_catalogmodel_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_flat',
            field=models.TextField(blank=True, null=True, verbose_name='Код Объекта'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name_flate',
            field=models.TextField(blank=True, null=True, verbose_name='Название кв'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tel',
            field=models.TextField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
