# Generated by Django 2.0.13 on 2020-08-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200804_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogmodel',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Объекты и добавление'},
        ),
    ]
