# Generated by Django 2.0.13 on 2020-08-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200804_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='float_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='goods',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
