# Generated by Django 2.0.13 on 2020-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200817_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogmodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='catalogmodel',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
    ]
