# Generated by Django 2.0.13 on 2020-08-23 08:59

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20200817_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='about_the_apartment',
            field=models.CharField(blank=True, max_length=3, verbose_name='Этажность в доме'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='pages',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Обязательно должно быть какое то видео', verbose_name='Видео'),
        ),
    ]
