# Generated by Django 2.0.13 on 2020-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200823_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='about_the_apartment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Этажность в доме и этаж квартиры'),
        ),
    ]
