# Generated by Django 2.0.13 on 2020-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200823_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='apartment_description',
            field=models.CharField(blank=True, max_length=30, verbose_name='Новострой или вторичка'),
        ),
    ]
