# Generated by Django 2.0.13 on 2020-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200824_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='object_type',
            field=models.CharField(choices=[('1', 'Жилая'), ('2', 'Нежилая'), ('3', 'VIP'), ('4', 'Sale')], default='1', max_length=255, verbose_name='Тип объекта'),
        ),
    ]
