# Generated by Django 2.0.13 on 2020-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200824_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='float_name',
            field=models.CharField(blank=True, help_text='Адрес', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='object_type',
            field=models.CharField(blank=True, help_text='вписать любое: значение Жилая Нежилая VIP Sale', max_length=255, verbose_name='Тип объекта'),
        ),
    ]
