# Generated by Django 2.0.13 on 2020-08-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200829_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='city',
            field=models.CharField(blank=True, max_length=15, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='float_name',
            field=models.CharField(blank=True, help_text='Адрес', max_length=20, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='goods',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='pages',
            field=models.CharField(blank=True, help_text='Вписать район', max_length=20, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='catalogmodel',
            name='quadrature',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квадратура'),
        ),
    ]
